-- ---------------------------
-- 10 Advanced Business Problems
-- ---------------------------

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

-- Step 1: Add a new float column
-- Step 2: Update it with calculated values

-----------------------------------------------------------------------------

/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/



-----------------------------------------------------------------------------

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/



-----------------------------------------------------------------------------
-- Problem 4
-- Monthly Sales Trend
-- Query monthly total sales over the past year.
-- Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!




-----------------------------------------------------------------------------

/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
*/




-----------------------------------------------------------------------------

/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/



-----------------------------------------------------------------------------

/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

-----------------------------------------------------------------------------

/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

-----------------------------------------------------------------------------

/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/


	
-----------------------------------------------------------------------------

/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

-----------------------------------------------------------------------------


/*
11. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/

-----------------------------------------------------------------------------


 /*
 12.
Most Returned Products
Query the top 10 products by the number of returns.
Challenge : Display the return rate as a percentage of total units sold for each product.
*/


-----------------------------------------------------------------------------


/*
13. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/

-----------------------------------------------------------------------------
