-- ---------------------------
-- 10 Advanced Business Problems
-- ---------------------------

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

-- Step 1: Add a new float column
ALTER TABLE order_items
ADD total_sales FLOAT;

-- Step 2: Update it with calculated values
UPDATE order_items
SET total_sales = quantity * price_per_unit;



select  top 10 oi.product_id,p.product_name,
 sum(oi.total_sales) as Total_sales_value,count(o.order_id) as Total_Quantity_sold 
from order_items as oi
join orders as o
on o.order_id = oi.order_id
join products as p
on p.product_id=oi.product_id
group by oi.product_id,product_name
order by 3 desc;

-----------------------------------------------------------------------------

/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

select *,ROUND((Sales_by_category * 100.0 / SUM(Sales_by_category) OVER ()), 2) AS percentage_contributionn from

(select c.category_id,c.category_name,Round(sum(oi.total_sales),2) as Sales_by_category from Category as c
JOIN products as p
on c.category_id = p.category_id
JOIN order_items as oi
on oi.product_id = p.product_id
group by c.category_id,c.category_name)t
Order by Sales_by_category desc;

-----------------------------------------------------------------------------

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/

SELECT c.customer_id,concat(c.first_name,' ',c.last_name)as Names ,
avg(oi.total_sales) as Average_Order_value,
count(o.order_id) as Total_orders
FROM customers as c
LEFT JOIN Orders as o
ON c.customer_id = o.customer_id
LEFT JOIN order_items as oi
ON o.order_id = oi.order_id
Group by c.customer_id,concat(c.first_name,' ',c.last_name)
Having count(o.order_id) >5;

-----------------------------------------------------------------------------
-- Problem 4
-- Monthly Sales Trend
-- Query monthly total sales over the past year.
-- Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!


with Monthly_trend as (
select  top 12 Year(o.order_date) as YEAR,
Datename(Month,o.Order_date) as Month,
Month(o.Order_date) as Month_Number,
ROUND(sum(oi.total_sales),2) as Sales_by_Month
from Orders as o
LEFT JOIN Order_items as oi
ON o.order_id = oi.order_id
Group by Year(o.order_date),Month(o.Order_date),Datename(Month,o.Order_date)
Order by Year(o.order_date) desc,Month(o.Order_date)desc,Datename(Month,o.Order_date)desc
)

select *,(select
	top 1 Sales_by_Month from Monthly_trend) Current_month_sales,
	lead(Sales_by_Month,1,null) over(order by year desc) as Last_Month_sales 
from Monthly_trend
;
-----------------------------------------------------------------------------

/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
*/


select distinct c.customer_id,
concat(c.first_name,' ',c.last_name) Full_Name,state from customers as c
left join orders as o
on c.customer_id = o.customer_id
where order_id is null;


-----------------------------------------------------------------------------

/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/


select *
 from (
select c.State,ca.category_name,Sum(total_sales) Total_sales_state_category,
Rank() over(partition by state order by Sum(total_sales) asc) as ranks from customers c
 Inner join orders as o 
on c.customer_id = o.customer_id
 Inner join order_items as oi
on oi.order_id = o.order_id
 Inner join products as p
on p.product_id = oi.product_id
Inner join category as ca
on ca.category_id = p.category_id
Group by state,category_name
)t
where ranks = 1 ;


-----------------------------------------------------------------------------

/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/
select *,
	Dense_rank() over(order by total_order_value desc) as Ranks from (
select 
	c.customer_id,
	concat(c.first_name, ' ', c.last_name) as Fullname,
	sum(total_sales) as Total_Order_value from Customers as c
Inner join orders as o
on c.customer_id = o.customer_id
left join order_items as oi
on o.order_id = oi.order_id
group by c.customer_id,concat(c.first_name, ' ', c.last_name)
)t;


-----------------------------------------------------------------------------

/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

Select p.product_id, p.product_name,i.stock as current_stock,i.last_stock_date,i.warehouse_id from products as p
Left join inventory as i
on p.product_id = i.product_id
where stock <10
Order By stock asc;

-----------------------------------------------------------------------------

/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/

    select c.*,o.order_id,o.order_date,s.shipping_date,s.shipping_providers,
	datediff(day,o.order_date,s.shipping_date) as Shipping_day_difference from Orders as o
	join customers as c
	on o.customer_id = c.customer_id
	full join shippings as s
	on o.order_id = s.order_id
	where s.shipping_date is not null and datediff(day,o.order_date,s.shipping_date) >3;
	
-----------------------------------------------------------------------------

/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

select p.payment_status,
count (*) as count_of_payment_status,
cast(count(*) as float)/cast((select count(*) from payments) as float) * 100 as payment_percentage
from orders as o
join payments as p
on p.order_id = o.order_id
group by payment_status
order by payment_percentage desc;


/*
11. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/

select 
	p.product_id,
	p.product_name,
	sum(total_sales -	(p.cogs *oi.quantity) )as profit,
	sum(total_sales -	(p.cogs *oi.quantity) )/sum(total_sales) *100 as profit_margin
	,DENSE_RANK ()over (order by sum(total_sales -	(p.cogs *oi.quantity) )/sum(total_sales) *100 desc) as ranking
from order_items as oi
JOIN products as p
on oi.product_id = p.product_id
Group by p.product_id,p.product_name ;

select * from products;

 /*
 12.
Most Returned Products
Query the top 10 products by the number of returns.
Challenge : Display the return rate as a percentage of total units sold for each product.
*/

SELECT 
    p.product_id,
    p.product_name,
    COUNT(*) AS total_unit_sold,
    SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS total_returned,
    CAST(SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS DECIMAL(10,2)) /
    CAST(COUNT(*) AS DECIMAL(10,2)) * 100 AS return_percentage
FROM order_items AS oi
INNER JOIN products AS p
    ON oi.product_id = p.product_id
INNER JOIN orders AS o
    ON o.order_id = oi.order_id
GROUP BY p.product_id, p.product_name
ORDER BY return_percentage DESC;



/*
13. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/
SELECT
c.state,
CONCAT (c. first_name,' ', c.last_name) as customers,
COUNT (o.order_id) as total_orders,
SUM(total_sales) as total_sale,
DENSE_RANK() OVER(PARTITION BY c. state ORDER BY COUNT (o.order_id) DESC) as rank
FROM orders as o
JOIN
order_items as oi
ON oi.order_id = o.order_id
JOIN
customers as c
ON
c. customer_id = o. customer_id
GROUP BY c.state,
CONCAT (c. first_name,' ', c.last_name)